# Generated by Selenium IDE
import pytest
import time

import yaml
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestDemo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
  
  def teardown_method(self, method):
    self.driver.quit()

  def test_demo(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.find_element(By.ID, "kw").click()
    self.driver.find_element(By.ID, "kw").send_keys("霍格沃兹测试学院")
    self.driver.find_element(By.ID, "su").click()
    # time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "霍格沃兹测试学院 – 测试开发工程师的黄埔军校").click()

def test_wework():
  # 调用chromeoptions方法
  opt = webdriver.ChromeOptions()
  # 设置复用浏览器的地址
  opt.debugger_address = "127.0.0.1:9222"
  driver = webdriver.Chrome(options=opt)
  # 设置隐式等待
  driver.implicitly_wait(10)
  # 打开企业微信主页
  driver.get("https://work.weixin.qq.com/wework_admin/frame#index")
  # 点击通讯录
  driver.find_element_by_id("menu_contacts").click()
  time.sleep(3)

# 获取cookie序列化后存入yaml
def test_get_cookie():
  # 调用chromeoptions方法
  opt = webdriver.ChromeOptions()
  # 设置复用浏览器的地址
  opt.debugger_address = "127.0.0.1:9222"
  driver = webdriver.Chrome(options=opt)
  # 设置隐式等待
  driver.implicitly_wait(10)
  cookies = driver.get_cookies()
  with open("data.yaml", "w",encoding="utf-8") as f:
    # 快捷键导包：mac option+enter，win： alt + enter
    # 序列化cookie，存入yaml文件
    yaml.dump(cookies,f)

# 从yaml里读取cookie登录
def test_login():
  driver = webdriver.Chrome()
  # 设置cookie前访问企业微信扫码登录页面
  driver.get("https://work.weixin.qq.com/wework_admin/loginpage_wx")
  # 打开yaml文件，读取cookie信息，赋值给yaml_date
  with open("data.yaml",encoding="utf-8") as f:
    yaml_date = yaml.safe_load(f)
  for cookie in yaml_date:
    # 把cookie传给driver
    driver.add_cookie(cookie)
  # 设置cookie后，再次访问企业微信
  driver.get("https://work.weixin.qq.com/wework_admin/frame#index")
  time.sleep(3)
